name: CI/CD for Artifact Approvals

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/python-template.yml
    with:
      python_dir: "./python-app"

  push-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: ./dist
      - name: Log in to Artifact Registry / Docker Hub
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" \
          | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.REGISTRY_URL }}/my-python-app:${{ github.sha }}
          docker build -t $IMAGE ./dist
          docker push $IMAGE
      - name: Save image name for later jobs
        run: echo "image=${{ secrets.REGISTRY_URL }}/my-python-app:${{ github.sha }}" >> $GITHUB_ENV

  deploy-dev:
    needs: push-artifact
    uses: ./.github/workflows/deploy-dev.yml
    with:
      image: ${{ env.image }}

  deploy-uat:
    needs: deploy-dev
    uses: ./.github/workflows/deploy-uat.yml
    with:
      image: ${{ env.image }}

